#!/bin/bash
# Generate SVGs from all hand-crafted PlantUML diagrams.
# Source:  architecture/diagrams/**/*.puml  (architect-edited)
# Output:  portal/docs/diagrams/svg/        (generated by CI)
set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"
SRC="$ROOT/architecture/diagrams"
OUT="$ROOT/portal/docs/diagrams/svg"

mkdir -p "$OUT"

count=0
while IFS= read -r -d '' f; do
  name=$(basename "$f" .puml)
  echo "Generating: $name"
  plantuml -tsvg -o "$OUT" "$f"
  echo "  -> OK"
  count=$((count + 1))
done < <(find "$SRC" -name "*.puml" ! -name "include.puml" ! -name "templates.puml" -print0)

echo ""
echo "Generated $count SVG files from architecture/diagrams/"
