@startuml
!include <c4/C4_Container>

LAYOUT_WITH_LEGEND()
LAYOUT_TOP_DOWN()

title svc-inventory-procurement — Integration Context

Person(web_ops_dashboard, "Operations Dashboard", "Web App", $link="/applications/web-ops-dashboard/#service-dependencies")

System_Boundary(boundary, "NovaTrek Platform") {
    Container(svc_inventory_procurement, "svc-inventory-procurement", "Java / Spring Boot", "Inventory Procurement Service", $link="/microservices/svc-inventory-procurement/")
    ContainerDb(svc_inventory_procurement_db, "PostgreSQL 15", "procurement schema", "Primary data store", $link="/microservices/svc-inventory-procurement/#data-store")
    Container(svc_gear_inventory, "svc-gear-inventory", "Java / Spring Boot", "Logistics", $link="/microservices/svc-gear-inventory/#integration-context")
    Container(svc_notifications, "svc-notifications", "Java / Spring Boot", "Support", $link="/microservices/svc-notifications/#integration-context")
    Container(svc_payments, "svc-payments", "Java / Spring Boot", "Support", $link="/microservices/svc-payments/#integration-context")
}


Rel(web_ops_dashboard, svc_inventory_procurement, "Uses API", "HTTPS")
Rel(svc_inventory_procurement, svc_inventory_procurement_db, "Reads/Writes", "SQL/TCP")
Rel(svc_inventory_procurement, svc_gear_inventory, "Verify item catalog", "HTTPS")
Rel(svc_inventory_procurement, svc_notifications, "Notify procurement team", "HTTPS")
Rel(svc_inventory_procurement, svc_payments, "Process PO payment", "HTTPS")

@enduml