@startuml
!include <c4/C4_Container>

LAYOUT_WITH_LEGEND()
LAYOUT_TOP_DOWN()

header [[/microservices/ ⬆ All Microservices]]

title svc-trip-catalog — Integration Context

Person(app_guest_mobile, "Adventure App", "Mobile App", $link="/applications/app-guest-mobile/#service-dependencies")
Person(web_guest_portal, "Guest Portal", "Web App", $link="/applications/web-guest-portal/#service-dependencies")

System_Boundary(boundary, "NovaTrek Platform") {
    Container(svc_trip_catalog, "svc-trip-catalog", "Java / Spring Boot", "Trip Catalog Service", $link="/microservices/svc-trip-catalog/")
    ContainerDb(svc_trip_catalog_db, "PostgreSQL 15", "catalog schema", "Primary data store", $link="/microservices/svc-trip-catalog/#data-store")
    Container(svc_check_in, "svc-check-in", "Java / Spring Boot", "Operations", $link="/microservices/svc-check-in/#integration-context")
    Container(svc_partner_integrations, "svc-partner-integrations", "Java / Spring Boot", "External", $link="/microservices/svc-partner-integrations/#integration-context")
    Container(svc_reservations, "svc-reservations", "Java / Spring Boot", "Booking", $link="/microservices/svc-reservations/#integration-context")
    Container(svc_scheduling_orchestrator, "svc-scheduling-orchestrator", "Java / Spring Boot", "Operations", $link="/microservices/svc-scheduling-orchestrator/#integration-context")
}


Rel(app_guest_mobile, svc_trip_catalog, "Uses API", "HTTPS")
Rel(web_guest_portal, svc_trip_catalog, "Uses API", "HTTPS")
Rel(svc_check_in, svc_trip_catalog, "Get adventure category", "HTTPS")
Rel(svc_partner_integrations, svc_trip_catalog, "Check trip availability", "HTTPS")
Rel(svc_reservations, svc_trip_catalog, "2 calls", "HTTPS")
Rel(svc_scheduling_orchestrator, svc_trip_catalog, "2 calls", "HTTPS")
Rel(svc_trip_catalog, svc_trip_catalog_db, "Reads/Writes", "SQL/TCP")

@enduml