spring:
  config:
    activate:
      on-profile: dev

  datasource:
    url: jdbc:postgresql://${DATABASE_HOST}:5432/novatrek_dev
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2

logging:
  level:
    com.novatrek: DEBUG
