server:
  port: 8082

spring:
  application:
    name: svc-guest-profiles
  datasource:
    url: jdbc:postgresql://localhost:5432/novatrek_guests
    username: ${DB_USERNAME:novatrek}
    password: ${DB_PASSWORD:novatrek}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: when-authorized

logging:
  level:
    com.novatrek: INFO
    org.springframework.web: WARN
