server:
  port: 8083

spring:
  application:
    name: svc-check-in
  datasource:
    url: jdbc:postgresql://localhost:5432/checkin_db
    username: ${DB_USERNAME:checkin_user}
    password: ${DB_PASSWORD:checkin_pass}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

novatrek:
  services:
    reservations-url: ${RESERVATIONS_SERVICE_URL:http://localhost:8082}
