site_name: NovaTrek Architecture Portal
site_description: Enterprise Architecture Knowledge Base — NovaTrek Adventures
site_url: https://placeholder.azurestaticapps.net
copyright: "&copy; 2026 NovaTrek Adventures — Architecture Practice"

theme:
  name: material
  language: en
  font:
    text: Inter
    code: JetBrains Mono
  icon:
    logo: material/compass-rose
    repo: fontawesome/brands/git-alt
  favicon: assets/favicon.png
  palette:
    - scheme: novatrek
      primary: custom
      accent: custom
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - scheme: slate
      primary: custom
      accent: custom
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
  features:
    - navigation.instant
    - navigation.instant.progress
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.expand
    - navigation.path
    - navigation.indexes
    - navigation.top
    - navigation.footer
    - search.suggest
    - search.highlight
    - search.share
    - content.code.copy
    - content.code.annotate
    - content.tabs.link
    - toc.follow
    - announce.dismiss

extra_css:
  - stylesheets/custom.css

extra:
  generator: false
  social:
    - icon: fontawesome/solid/mountain-sun
      link: https://novatrek.example.com
      name: NovaTrek Adventures
  status:
    new: Recently added
    deprecated: No longer maintained

plugins:
  - search:
      separator: '[\s\-\.]+'
  - tags
  - minify:
      minify_html: true

markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - tables
  - toc:
      permalink: true
      toc_depth: 3
  - pymdownx.betterem
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.smartsymbols
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

nav:
  - Home: index.md
  - Tags: tags.md
