@startuml
!include <c4/C4_Container>

LAYOUT_WITH_LEGEND()
LAYOUT_TOP_DOWN()

title svc-payments — Integration Context

Person(app_guest_mobile, "Adventure App", "Mobile App")
Person(web_guest_portal, "Guest Portal", "Web App")
Person(web_ops_dashboard, "Operations Dashboard", "Web App")

System_Boundary(boundary, "NovaTrek Platform") {
    Container(svc_payments, "svc-payments", "Java / Spring Boot", "Payments Service")
    ContainerDb(svc_payments_db, "PostgreSQL 15", "payments schema", "Primary data store")
    Container(svc_inventory_procurement, "svc-inventory-procurement", "Java / Spring Boot", "Support")
    Container(svc_loyalty_rewards, "svc-loyalty-rewards", "Java / Spring Boot", "Support")
    Container(svc_partner_integrations, "svc-partner-integrations", "Java / Spring Boot", "External")
    Container(svc_reservations, "svc-reservations", "Java / Spring Boot", "Booking")
    Container(svc_notifications, "svc-notifications", "Java / Spring Boot", "Support")
}

System_Ext(Fraud_Detection_API, "Fraud Detection API", "Third-party service")
System_Ext(Stripe_API, "Stripe API", "Third-party service")

Rel(app_guest_mobile, svc_payments, "Uses API", "HTTPS")
Rel(web_guest_portal, svc_payments, "Uses API", "HTTPS")
Rel(web_ops_dashboard, svc_payments, "Uses API", "HTTPS")
Rel(svc_inventory_procurement, svc_payments, "Process PO payment", "HTTPS")
Rel(svc_loyalty_rewards, svc_payments, "Process reward credit", "HTTPS")
Rel(svc_partner_integrations, svc_payments, "Process commission", "HTTPS")
Rel(svc_reservations, svc_payments, "Process deposit payment", "HTTPS")
Rel(svc_payments, svc_payments_db, "Reads/Writes", "SQL/TCP")
Rel(svc_payments, svc_notifications, "2 calls", "HTTPS")
Rel(svc_payments, Fraud_Detection_API, "Screen transaction", "HTTPS")
Rel(svc_payments, Stripe_API, "Process payment, Process refund", "HTTPS")

@enduml