@startuml
!include <c4/C4_Container>

LAYOUT_WITH_LEGEND()
LAYOUT_TOP_DOWN()

title svc-check-in — Integration Context

Person(app_guest_mobile, "Adventure App", "Mobile App")
Person(web_ops_dashboard, "Operations Dashboard", "Web App")

System_Boundary(boundary, "NovaTrek Platform") {
    Container(svc_check_in, "svc-check-in", "Java / Spring Boot", "Check In Service")
    ContainerDb(svc_check_in_db, "PostgreSQL 15", "checkin schema", "Primary data store")
    Container(svc_gear_inventory, "svc-gear-inventory", "Java / Spring Boot", "Logistics")
    Container(svc_guest_profiles, "svc-guest-profiles", "Java / Spring Boot", "Guest Identity")
    Container(svc_notifications, "svc-notifications", "Java / Spring Boot", "Support")
    Container(svc_reservations, "svc-reservations", "Java / Spring Boot", "Booking")
    Container(svc_safety_compliance, "svc-safety-compliance", "Java / Spring Boot", "Safety")
    Container(svc_trip_catalog, "svc-trip-catalog", "Java / Spring Boot", "Product Catalog")
}


Rel(app_guest_mobile, svc_check_in, "Uses API", "HTTPS")
Rel(web_ops_dashboard, svc_check_in, "Uses API", "HTTPS")
Rel(svc_check_in, svc_check_in_db, "Reads/Writes", "SQL/TCP")
Rel(svc_check_in, svc_gear_inventory, "Verify gear assignment", "HTTPS")
Rel(svc_check_in, svc_guest_profiles, "Validate guest identity", "HTTPS")
Rel(svc_check_in, svc_notifications, "Send check-in confirmation", "HTTPS")
Rel(svc_check_in, svc_reservations, "Verify reservation exists", "HTTPS")
Rel(svc_check_in, svc_safety_compliance, "2 calls", "HTTPS")
Rel(svc_check_in, svc_trip_catalog, "Get adventure category", "HTTPS")

@enduml