@startuml
!include <c4/C4_Container>

LAYOUT_WITH_LEGEND()
LAYOUT_TOP_DOWN()

header [[/microservices/ ⬆ All Microservices]]

title svc-media-gallery — Integration Context

Person(app_guest_mobile, "Adventure App", "Mobile App", $link="/applications/app-guest-mobile/#service-dependencies")
Person(web_guest_portal, "Guest Portal", "Web App", $link="/applications/web-guest-portal/#service-dependencies")

System_Boundary(boundary, "NovaTrek Platform") {
    Container(svc_media_gallery, "svc-media-gallery", "Java / Spring Boot", "Media Gallery Service", $link="/microservices/svc-media-gallery/")
    ContainerDb(svc_media_gallery_db, "PostgreSQL 15 + S3-Compatible Object Store", "media schema", "Primary data store", $link="/microservices/svc-media-gallery/#data-store")
    Container(svc_notifications, "svc-notifications", "Java / Spring Boot", "Support", $link="/microservices/svc-notifications/#integration-context")
}

System_Ext(Google_Maps_Platform, "Google Maps Platform", "Third-party service")

Rel(app_guest_mobile, svc_media_gallery, "Uses API", "HTTPS")
Rel(web_guest_portal, svc_media_gallery, "Uses API", "HTTPS")
Rel(svc_media_gallery, svc_media_gallery_db, "Reads/Writes", "SQL/TCP")
Rel(svc_media_gallery, svc_notifications, "Send share link", "HTTPS")
Rel(svc_media_gallery, Google_Maps_Platform, "Reverse geocode GPS metadata", "HTTPS")

@enduml