name: "svc-trip-catalog"

on:
  push:
    branches: [main]
    paths:
      - 'services/svc-trip-catalog/**'
      - '.github/workflows/service-ci.yml'
      - '.github/workflows/service-svc-trip-catalog.yml'
  pull_request:
    paths:
      - 'services/svc-trip-catalog/**'
      - '.github/workflows/service-ci.yml'
      - '.github/workflows/service-svc-trip-catalog.yml'

jobs:
  ci:
    uses: ./.github/workflows/service-ci.yml
    with:
      service-name: svc-trip-catalog
    secrets: inherit
