name: "svc-gear-inventory"

on:
  push:
    branches: [main]
    paths:
      - 'services/svc-gear-inventory/**'
      - '.github/workflows/service-ci.yml'
      - '.github/workflows/service-svc-gear-inventory.yml'
  pull_request:
    paths:
      - 'services/svc-gear-inventory/**'
      - '.github/workflows/service-ci.yml'
      - '.github/workflows/service-svc-gear-inventory.yml'

jobs:
  ci:
    uses: ./.github/workflows/service-ci.yml
    with:
      service-name: svc-gear-inventory
    secrets: inherit
