name: "svc-guest-profiles"

on:
  push:
    branches: [main]
    paths:
      - 'services/svc-guest-profiles/**'
      - '.github/workflows/service-ci.yml'
      - '.github/workflows/service-svc-guest-profiles.yml'
  pull_request:
    paths:
      - 'services/svc-guest-profiles/**'
      - '.github/workflows/service-ci.yml'
      - '.github/workflows/service-svc-guest-profiles.yml'

jobs:
  ci:
    uses: ./.github/workflows/service-ci.yml
    with:
      service-name: svc-guest-profiles
    secrets: inherit
